[2024-02-25T11:31:29.215+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing_sales.transform_data_to_silver scheduled__2022-09-01T01:00:00+00:00 [queued]>
[2024-02-25T11:31:29.225+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing_sales.transform_data_to_silver scheduled__2022-09-01T01:00:00+00:00 [queued]>
[2024-02-25T11:31:29.226+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-02-25T11:31:29.244+0000] {taskinstance.py:2192} INFO - Executing <Task(BigQueryInsertJobOperator): transform_data_to_silver> on 2022-09-01 01:00:00+00:00
[2024-02-25T11:31:29.252+0000] {standard_task_runner.py:60} INFO - Started process 463 to run task
[2024-02-25T11:31:29.255+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing_sales', 'transform_data_to_silver', 'scheduled__2022-09-01T01:00:00+00:00', '--job-id', '113', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpvx7bnkyv']
[2024-02-25T11:31:29.257+0000] {standard_task_runner.py:88} INFO - Job 113: Subtask transform_data_to_silver
[2024-02-25T11:31:29.321+0000] {task_command.py:423} INFO - Running <TaskInstance: processing_sales.transform_data_to_silver scheduled__2022-09-01T01:00:00+00:00 [running]> on host 9e4f31030bba
[2024-02-25T11:31:29.407+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing_sales' AIRFLOW_CTX_TASK_ID='transform_data_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2022-09-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-09-01T01:00:00+00:00'
[2024-02-25T11:31:29.420+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-25T11:31:29.424+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-02-25T11:31:29.426+0000] {bigquery.py:2806} INFO - Executing: {'query': {'query': "\n                    INSERT INTO `de-07-natalia-sokil.silver.sales` (client_id, purchase_date, product_name, price)\n                    SELECT\n                        CustomerId AS client_id,\n                        PARSE_DATE('%Y-%m-%d', PurchaseDate) AS purchase_date,\n                        Product AS product_name,\n                        CAST(Price AS FLOAT64) AS price\n                    FROM `de-07-nataliia-sokil.bronze.sales`\n                ", 'useLegacySql': False}}'
[2024-02-25T11:31:29.478+0000] {bigquery.py:1596} INFO - Inserting job ***_processing_sales_transform_data_to_silver_2022_09_01T01_00_00_00_00_5b98a71cb21be475e5b0f09f43a35b15
[2024-02-25T11:31:30.115+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2864, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.NotFound: 404 Not found: Table de-07-natalia-sokil:silver.sales was not found in location EU

Location: EU
Job ID: airflow_processing_sales_transform_data_to_silver_2022_09_01T01_00_00_00_00_5b98a71cb21be475e5b0f09f43a35b15

[2024-02-25T11:31:30.128+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processing_sales, task_id=transform_data_to_silver, execution_date=20220901T010000, start_date=20240225T113129, end_date=20240225T113130
[2024-02-25T11:31:30.144+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 113 for task transform_data_to_silver (404 Not found: Table de-07-natalia-sokil:silver.sales was not found in location EU

Location: EU
Job ID: airflow_processing_sales_transform_data_to_silver_2022_09_01T01_00_00_00_00_5b98a71cb21be475e5b0f09f43a35b15
; 463)
[2024-02-25T11:31:30.191+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-25T11:31:30.211+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-02-25T11:54:47.323+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing_sales.transform_data_to_silver scheduled__2022-09-01T01:00:00+00:00 [queued]>
[2024-02-25T11:54:47.333+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing_sales.transform_data_to_silver scheduled__2022-09-01T01:00:00+00:00 [queued]>
[2024-02-25T11:54:47.334+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 4
[2024-02-25T11:54:47.351+0000] {taskinstance.py:2192} INFO - Executing <Task(BigQueryInsertJobOperator): transform_data_to_silver> on 2022-09-01 01:00:00+00:00
[2024-02-25T11:54:47.356+0000] {standard_task_runner.py:60} INFO - Started process 828 to run task
[2024-02-25T11:54:47.360+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing_sales', 'transform_data_to_silver', 'scheduled__2022-09-01T01:00:00+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmp4ojor7e5']
[2024-02-25T11:54:47.362+0000] {standard_task_runner.py:88} INFO - Job 119: Subtask transform_data_to_silver
[2024-02-25T11:54:47.418+0000] {task_command.py:423} INFO - Running <TaskInstance: processing_sales.transform_data_to_silver scheduled__2022-09-01T01:00:00+00:00 [running]> on host 9e4f31030bba
[2024-02-25T11:54:47.512+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing_sales' AIRFLOW_CTX_TASK_ID='transform_data_to_silver' AIRFLOW_CTX_EXECUTION_DATE='2022-09-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-09-01T01:00:00+00:00'
[2024-02-25T11:54:47.525+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-25T11:54:47.530+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-02-25T11:54:47.532+0000] {bigquery.py:2806} INFO - Executing: {'query': {'query': "\n                    INSERT INTO `de-07-natalia-sokil.silver.sales` (client_id, purchase_date, product_name, price)\n                    SELECT\n                        CustomerId AS client_id,\n                        PARSE_DATE('%Y-%m-%d', PurchaseDate) AS purchase_date,\n                        Product AS product_name,\n                        CAST(Price AS FLOAT64) AS price\n                    FROM `de-07-nataliia-sokil.bronze.sales`\n                ", 'useLegacySql': False}}'
[2024-02-25T11:54:47.588+0000] {bigquery.py:1596} INFO - Inserting job ***_processing_sales_transform_data_to_silver_2022_09_01T01_00_00_00_00_d38330eb76c38a96ca465b1b14d580e8
[2024-02-25T11:54:48.479+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2864, in execute
    job.result(timeout=self.result_timeout, retry=self.result_retry)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1595, in result
    do_get_result()
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/query.py", line 1584, in do_get_result
    super(QueryJob, self).result(retry=retry, timeout=timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/cloud/bigquery/job/base.py", line 952, in result
    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/google/api_core/future/polling.py", line 261, in result
    raise self._exception
google.api_core.exceptions.Forbidden: 403 Access Denied: Table de-07-nataliia-sokil:bronze.sales: User does not have permission to query table de-07-nataliia-sokil:bronze.sales, or perhaps it does not exist in location EU.

Location: EU
Job ID: airflow_processing_sales_transform_data_to_silver_2022_09_01T01_00_00_00_00_d38330eb76c38a96ca465b1b14d580e8

[2024-02-25T11:54:48.512+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processing_sales, task_id=transform_data_to_silver, execution_date=20220901T010000, start_date=20240225T115447, end_date=20240225T115448
[2024-02-25T11:54:48.539+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 119 for task transform_data_to_silver (403 Access Denied: Table de-07-nataliia-sokil:bronze.sales: User does not have permission to query table de-07-nataliia-sokil:bronze.sales, or perhaps it does not exist in location EU.

Location: EU
Job ID: airflow_processing_sales_transform_data_to_silver_2022_09_01T01_00_00_00_00_d38330eb76c38a96ca465b1b14d580e8
; 828)
[2024-02-25T11:54:48.577+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-25T11:54:48.596+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
