[2024-02-20T21:37:58.725+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-20T21:37:58.735+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-20T21:37:58.735+0000] {taskinstance.py:2171} INFO - Starting attempt 17 of 20
[2024-02-20T21:37:58.754+0000] {taskinstance.py:2192} INFO - Executing <Task(GCSToBigQueryOperator): load_data_to_bronze> on 2022-08-01 01:00:00+00:00
[2024-02-20T21:37:58.762+0000] {standard_task_runner.py:60} INFO - Started process 1095 to run task
[2024-02-20T21:37:58.766+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing_sales', 'load_data_to_bronze', 'scheduled__2022-08-01T01:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmprblmh7fp']
[2024-02-20T21:37:58.767+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask load_data_to_bronze
[2024-02-20T21:37:58.839+0000] {task_command.py:423} INFO - Running <TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [running]> on host 14ee3b1c5c12
[2024-02-20T21:37:58.930+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing_sales' AIRFLOW_CTX_TASK_ID='load_data_to_bronze' AIRFLOW_CTX_EXECUTION_DATE='2022-08-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='17' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-01T01:00:00+00:00'
[2024-02-20T21:37:58.943+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-20T21:37:58.947+0000] {base.py:83} INFO - Using connection ID 'google-cloud' for task execution.
[2024-02-20T21:37:58.948+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-02-20T21:37:58.949+0000] {logging_mixin.py:188} INFO - VEFORE
[2024-02-20T21:37:58.950+0000] {logging_mixin.py:188} INFO - path /opt/***/etc/credentials.json
[2024-02-20T21:37:58.951+0000] {logging_mixin.py:188} INFO - dict ***
[2024-02-20T21:37:58.955+0000] {logging_mixin.py:188} INFO - {'key_path': '/opt/***/etc/credentials.json', 'keyfile_dict': '{   "type": "service_account",   "project_id": "de-07-natalia-sokil",   "private_key_id": "d83892605d061c9b801620e6060fd877513f52aa",   "private_key": "-----BEGIN PRIVATE KEY-----\\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCccawS8eAcdaap\\nLZKrN86P5aHKkJfTYH/+AF8C8F/yduhkQSI/QJBLnf7cdNY3lPNAhS1TeOvgSJsT\\nwHFVUyTd5hTK1Ssz57a7Yd9Hh+AL9zSZX2QfZk0qknYI19VM5JxC728N3BGkLXPA\\n0yNXBxZig+7fAzxB7g7XSsD71gHIchbUNvtfQlDHiVk5vhxvIlbKKO3VrFd0SzXx\\nyyXBGffdoGXegiLfASawG/7q7BDSrEVNJF1MLi6H0ohHweDYqF/DcZl0UY3c7X3r\\n+vX5wh5344N6UpeyNm8d64Kb1yaYVnJcKBQRn/Dkq8eZ+ElUClO8JaI3VvASkP6N\\ncrze0ZbdAgMBAAECggEACruBoosVZN5tYI3P0g8yDI0kXFEvGUE1hqdf3UPAUVH2\\n/2m4f75eJ9He+iDJ0WZWicaZJXDWPby9Zs18+O2LSe3O31tga18qGhDM0Itxw2Bi\\nK2Nv6veJs7H4hwLHj07fqXfjln/SdgDoQAI8GmxSDNAgQwxlxeAfBIYMVzqHRMjz\\nZSx+ISz2o5tQIvBp769yhzTR8iIXmFz2ooRlcjzb1AxT5xCrug49dadTLrsSFCeD\\neWHZp7awYwkwPlj9PRNfM4mLkxYUinC/x1UDeDzAXXw7f8C6EjD9foGVnsF23Krq\\nPQET0TN9OagPHj3DyYY6Da+KF1NIB8MCazTwtHUBwQKBgQDU5GkVnei9cxLEu5T8\\nzBIEiMvJfvyiP2Bs0HYuuXuoxOWcWItXRx7oW4pNthRx9WEI+IcN5jgagWee9MAF\\nJ36l7wmfttrJE5Pd1ggkw/e+SW4tcWpmRo2d8LCtfjSHGDRniLoI3C5dGQi9H3xP\\nqxY9nIHXBmJFT1x9OHGau9jsDwKBgQC8Hy8wl7jJ9ZrO5fypMnj2xfTDX5EXALqO\\n2o3oE1SgIHbrCc2jzuOjO7Lls5M/QAzZ41fmFcVVEM4G9Y5ojoJO2HaaRgZHCNI1\\n8iU4UDKnkfRednIcTPcvCqm+UhJcMMWihG/Rrxseb1Je2H+A/Rv31jYG7bBgVxMg\\n3T1+htwSUwKBgQDOWmeRUHJbz8KNdtU/A/8i7gW51aDDE3M/hgBH4fn+6Hs3RIwr\\nmQBYcQJpuOewXgwkSeF+k3wmFPB/nvTRCis0Y7KMYQ1IgfV9vQw/tsPYagyld52O\\nbSyvvrFCOWZo3AlPobPRCrrV+oIB7xbrkgYIyj8AUWvHitk3dxKGzTXB+QKBgF1F\\n4PHo6BhKjD01TvbdLZi9QcR0581N8THPLzj4DKdwMUYMEEe91qQif2rghIuByF1o\\nGTbdaH/q2xwcOEWjEvzg2r1XJtmliARzUP0A1ny7IzyK4b0idBSA5vSUYMIQ9IzF\\nuWNvvLR0YZThJybfWDSjoxoAU8kQo01SJKFNYGQ9AoGBAJmcXkJu88YQyXXKEk4M\\nnJnIyx94lkFHMtV9FQpCt8z3MLAk5T8ndSjRHoE1ENa9BiK95t2W2IxD+p/xAEzF\\nJewE9C5zHB7n4Hk/MqU2zkE634XQTlJa8jLUhOwvqmg24PnAYTR5HzIt/q8ojh5G\\ncbQ/SujXDqzyOmIYV+EtqStm\\n-----END PRIVATE KEY-----\\n",   "client_email": "credentions@de-07-natalia-sokil.iam.gserviceaccount.com",   "client_id": "103811747982007749447",   "auth_uri": "https://accounts.google.com/o/oauth2/auth",   "token_uri": "https://oauth2.googleapis.com/token",   "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",   "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/credentions%40de-07-natalia-sokil.iam.gserviceaccount.com",   "universe_domain": "googleapis.com" }', 'num_retries': 5, 'credential_config_file': '/opt/***/etc/credentials.json', 'project': 'de-07-natalia-sokil', 'scope': 'https://www.googleapis.com/auth/cloud-platform'}
[2024-02-20T21:37:58.956+0000] {logging_mixin.py:188} INFO - ***
[2024-02-20T21:37:58.965+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 380, in execute
    self.configuration = self._use_existing_table()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/transfers/gcs_to_bigquery.py", line 581, in _use_existing_table
    default_project_id=self.hook.project_id,
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 370, in project_id
    _, project_id = self.get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 282, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 213, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-02-20T21:37:58.970+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processing_sales, task_id=load_data_to_bronze, execution_date=20220801T010000, start_date=20240220T213758, end_date=20240220T213758
[2024-02-20T21:37:58.982+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 31 for task load_data_to_bronze (The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 1095)
[2024-02-20T21:37:59.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-20T21:37:59.046+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
