[2024-02-20T21:25:34.298+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: processing_sales.load_data_to_bronze scheduled__2022-08-01T01:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
