[2024-02-25T11:09:50.462+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: processing_sales.create_bronze_dataset scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-25T11:09:50.468+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: processing_sales.create_bronze_dataset scheduled__2022-08-01T01:00:00+00:00 [queued]>
[2024-02-25T11:09:50.469+0000] {taskinstance.py:2171} INFO - Starting attempt 14 of 17
[2024-02-25T11:09:50.479+0000] {taskinstance.py:2192} INFO - Executing <Task(BigQueryCreateEmptyDatasetOperator): create_bronze_dataset> on 2022-08-01 01:00:00+00:00
[2024-02-25T11:09:50.484+0000] {standard_task_runner.py:60} INFO - Started process 100 to run task
[2024-02-25T11:09:50.487+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'processing_sales', 'create_bronze_dataset', 'scheduled__2022-08-01T01:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/process_sales.py', '--cfg-path', '/tmp/tmpldm1z86p']
[2024-02-25T11:09:50.488+0000] {standard_task_runner.py:88} INFO - Job 100: Subtask create_bronze_dataset
[2024-02-25T11:09:50.529+0000] {task_command.py:423} INFO - Running <TaskInstance: processing_sales.create_bronze_dataset scheduled__2022-08-01T01:00:00+00:00 [running]> on host 9e4f31030bba
[2024-02-25T11:09:50.587+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='processing_sales' AIRFLOW_CTX_TASK_ID='create_bronze_dataset' AIRFLOW_CTX_EXECUTION_DATE='2022-08-01T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='14' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-01T01:00:00+00:00'
[2024-02-25T11:09:50.596+0000] {connection.py:234} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-02-25T11:09:50.599+0000] {base.py:83} INFO - Using connection ID 'google_cloud_default' for task execution.
[2024-02-25T11:09:50.600+0000] {bigquery.py:469} INFO - datasetId was not specified in `dataset_reference`. Will use default value bronze.
[2024-02-25T11:09:50.600+0000] {bigquery.py:469} INFO - projectId was not specified in `dataset_reference`. Will use default value de-07-natalia-sokil.
[2024-02-25T11:09:50.601+0000] {bigquery.py:480} INFO - Creating dataset: bronze in project: de-07-natalia-sokil 
[2024-02-25T11:09:50.607+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 2014, in execute
    dataset = bq_hook.create_empty_dataset(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 475, in inner_wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 481, in create_empty_dataset
    dataset_object = self.get_client(project_id=project_id, location=location).create_dataset(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 162, in get_client
    credentials=self.get_credentials(),
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 296, in get_credentials
    credentials, _ = self.get_credentials_and_project_id()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/common/hooks/base_google.py", line 273, in get_credentials_and_project_id
    credentials, project_id = get_credentials_and_project_id(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 362, in get_credentials_and_project_id
    return _CredentialProvider(*args, **kwargs).get_credentials_and_project()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/google/cloud/utils/credentials_provider.py", line 213, in __init__
    raise AirflowException(
airflow.exceptions.AirflowException: The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.
[2024-02-25T11:09:50.612+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=processing_sales, task_id=create_bronze_dataset, execution_date=20220801T010000, start_date=20240225T110950, end_date=20240225T110950
[2024-02-25T11:09:50.620+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 100 for task create_bronze_dataset (The `keyfile_dict`, `key_path`, and `key_secret_name` fields are all mutually exclusive. Please provide only one value.; 100)
[2024-02-25T11:09:50.659+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-25T11:09:50.678+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
